/**
 * statusLine.ts — Claude Code status line integration for claude-drive.
 * Generates a bash script, installs/uninstalls it in ~/.claude/settings.json.
 */
import fs from "fs";
import path from "path";
import os from "os";
import { getConfig } from "./config.js";
import { getStatusFilePath } from "./statusFile.js";

const SCRIPT_PATH = path.join(os.homedir(), ".claude-drive", "statusline.sh");
const CLAUDE_SETTINGS_PATH = path.join(os.homedir(), ".claude", "settings.json");

export function getScriptPath(): string {
  return SCRIPT_PATH;
}

/** Generate the bash status line script content. */
export function generateStatusLineScript(): string {
  const statusFilePath = getStatusFilePath();
  const showModel = getConfig<boolean>("statusLine.showModel") ?? true;
  const showContext = getConfig<boolean>("statusLine.showContext") ?? true;
  const showCost = getConfig<boolean>("statusLine.showCost") ?? true;
  const showDriveState = getConfig<boolean>("statusLine.showDriveState") ?? true;
  const showOperatorTask = getConfig<boolean>("statusLine.showOperatorTask") ?? true;
  const maxTaskLength = getConfig<number>("statusLine.maxTaskLength") ?? 40;

  // Build the node script that will be exec'd
  const nodeScript = `
const fs = require('fs');
let cc = {};
try { cc = JSON.parse(fs.readFileSync(0, 'utf8')); } catch {}

function fmtCost(n) { return n >= 1 ? '$' + n.toFixed(2) : n >= 0.01 ? '$' + n.toFixed(3) : '$' + n.toFixed(4); }
function fmtDur(ms) { const s = Math.floor(ms / 1000); const m = Math.floor(s / 60); return m > 0 ? m + 'm' + (s % 60) + 's' : s + 's'; }

// Line 1: Claude Code session info
const parts = [];
${showModel ? `if (cc.model) parts.push(typeof cc.model === 'object' ? (cc.model.display_name || cc.model.id || '') : String(cc.model));` : ""}
${showContext ? `if (cc.context_window && cc.context_window.used_percentage != null) parts.push('ctx:' + Math.round(cc.context_window.used_percentage) + '%');` : ""}
${showCost ? `if (cc.cost && cc.cost.total_cost_usd != null) parts.push(fmtCost(cc.cost.total_cost_usd));` : ""}
${showCost ? `if (cc.cost && cc.cost.total_duration_ms != null) parts.push(fmtDur(cc.cost.total_duration_ms));` : ""}
if (parts.length > 0) console.log(parts.join('  '));

${showDriveState ? `
// Drive state
const STATUS_FILE = ${JSON.stringify(statusFilePath)};
try {
  const raw = fs.readFileSync(STATUS_FILE, 'utf8');
  const s = JSON.parse(raw);
  const stale = Date.now() - (s.updatedAt || 0) > 60000;
  if (stale) { console.log('Drive \\u25CB stale'); process.exit(0); }
  const icon = s.active ? '\\u25CF' : '\\u25CB';
  const mode = s.subMode || 'off';
  const t = s.totals || {};
  const totalCost = t.costUsd || 0;

  // Line 2: Drive header with total cost
  let header = 'Drive ' + icon + ' ' + mode;
  if (totalCost > 0) header += '  Total: ' + fmtCost(totalCost) + ' (' + (t.taskCount || 0) + ' tasks, ' + (t.turns || 0) + ' turns)';
  console.log(header);

  // Lines 3+: Per-operator stats
  const ops = s.operators || [];
  const fg = s.foregroundOperator || '';
  for (const op of ops) {
    const isFg = op.name === fg;
    const marker = isFg ? '\\u25B6' : ' ';
    const st = op.stats || {};
    let line = marker + ' ' + op.name;
    if (op.role) line += ' (' + op.role + ')';
    line += ' [' + op.status + ']';
    if (st.costUsd > 0) line += '  ' + fmtCost(st.costUsd) + '  ' + (st.turns || 0) + 'T  ' + fmtDur(st.durationMs || 0);
    ${showOperatorTask ? `if (op.task) line += '  \\u2192 ' + op.task.slice(0, ${maxTaskLength});` : ""}
    console.log(line);
  }

  // Plan cost line
  const cp = s.currentPlan;
  const lp = s.lastCompletedPlan;
  if (cp && cp.costUsd > 0) {
    console.log('Plan #' + cp.planIndex + ' (active): ' + fmtCost(cp.costUsd) + '  ' + cp.turns + 'T  ' + cp.taskCount + ' task(s)');
  } else if (lp && lp.costUsd > 0) {
    console.log('Plan #' + lp.planIndex + ' (done): ' + fmtCost(lp.costUsd) + '  ' + lp.turns + 'T  ' + lp.taskCount + ' task(s)');
  }
} catch {
  console.log('Drive \\u25CB offline');
}
` : ""}
`.trim();

  // Wrap in a bash script
  return `#!/usr/bin/env bash
# Generated by claude-drive. Regenerate with: claude-drive statusline install
# Do not edit manually — changes will be overwritten.
command -v node >/dev/null 2>&1 || { echo "Drive: node not found"; exit 0; }
exec node -e ${bashEscape(nodeScript)}
`;
}

/** Escape a string for use as a bash single-quoted argument. */
function bashEscape(s: string): string {
  // Use $'...' syntax with escaped single quotes and backslashes
  return "'" + s.replace(/'/g, "'\\''") + "'";
}

/** Install the status line script and patch ~/.claude/settings.json. */
export function installStatusLine(): { scriptPath: string; settingsPatched: boolean } {
  // 1. Write the script
  const scriptDir = path.dirname(SCRIPT_PATH);
  fs.mkdirSync(scriptDir, { recursive: true });
  fs.writeFileSync(SCRIPT_PATH, generateStatusLineScript(), "utf-8");
  fs.chmodSync(SCRIPT_PATH, 0o755);

  // 2. Patch Claude settings
  const settingsPatched = patchClaudeSettings(SCRIPT_PATH);

  return { scriptPath: SCRIPT_PATH, settingsPatched };
}

/** Remove the status line script and unpatch ~/.claude/settings.json. */
export function uninstallStatusLine(): { scriptRemoved: boolean; settingsPatched: boolean } {
  let scriptRemoved = false;
  try {
    fs.unlinkSync(SCRIPT_PATH);
    scriptRemoved = true;
  } catch {
    /* already gone */
  }

  const settingsPatched = unpatchClaudeSettings();
  return { scriptRemoved, settingsPatched };
}

function readClaudeSettings(): Record<string, unknown> {
  try {
    if (fs.existsSync(CLAUDE_SETTINGS_PATH)) {
      return JSON.parse(fs.readFileSync(CLAUDE_SETTINGS_PATH, "utf-8"));
    }
  } catch {
    /* corrupt or missing */
  }
  return {};
}

function writeClaudeSettings(settings: Record<string, unknown>): void {
  const dir = path.dirname(CLAUDE_SETTINGS_PATH);
  fs.mkdirSync(dir, { recursive: true });
  const tmp = CLAUDE_SETTINGS_PATH + ".tmp";
  fs.writeFileSync(tmp, JSON.stringify(settings, null, 2) + "\n", "utf-8");
  fs.renameSync(tmp, CLAUDE_SETTINGS_PATH);
}

function patchClaudeSettings(scriptPath: string): boolean {
  try {
    const settings = readClaudeSettings();
    const padding = getConfig<number>("statusLine.padding") ?? 2;
    settings.statusLine = {
      type: "command",
      command: scriptPath,
      padding,
    };
    writeClaudeSettings(settings);
    return true;
  } catch (e) {
    process.stderr.write(`[claude-drive] Failed to patch Claude settings: ${e}\n`);
    return false;
  }
}

function unpatchClaudeSettings(): boolean {
  try {
    const settings = readClaudeSettings();
    if (!settings.statusLine) return false;

    // Only remove if it points to our script
    const sl = settings.statusLine as Record<string, unknown>;
    if (sl.command && String(sl.command).includes(".claude-drive")) {
      delete settings.statusLine;
      writeClaudeSettings(settings);
      return true;
    }
    return false;
  } catch (e) {
    process.stderr.write(`[claude-drive] Failed to unpatch Claude settings: ${e}\n`);
    return false;
  }
}
